FROM node:20-alpine AS build
WORKDIR /app
COPY package*.json .
RUN npm ci
COPY . .
RUN npm run build

FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
# O entrypoint do nginx:alpine aplica envsubst automaticamente em /etc/nginx/templates/*.template
COPY nginx.conf.template /etc/nginx/templates/default.conf.template
EXPOSE 80 443
